In [5]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split as tts
from sklearn.metrics import accuracy_score
import numpy as np 
    
dating_set = pd.read_csv('Speed Dating Data.csv',usecols = ['gender','age_o','age','field_cd','dec_o'])
dating_set.drop_duplicates(inplace=True)
#print(dating_set)
#dating_set.replace('',np.nan, inplace = True)
dating_set = dating_set.dropna()
#dating_set
X = dating_set.drop(columns=['dec_o'])
y = dating_set['dec_o']

#X_train,X_test,y_train,y_test = tts(X,y,test_size = .8)

model = DecisionTreeClassifier()
model.fit(X,y)

#my_test = [[0,18,31],[0,19,31],[
 #   0,20,31],[0,21,31],[0,22,31],[0,23,31],[0,24,31],[0,25,31],[0,26,31],[0,27,31],[0,28,31],[0,29,31],[0,30,31],[0,31,31],[0,32,31],[0,31,33]]

my_age = 32
data_set = []
gender = 0
field_cd = 5
for age in range(18,my_age + 3):
    set = [] 
    set.append(gender)
    set.append(age)
    set.append(my_age)
    set.append(field_cd)
    data_set.append(set)
        
print(data_set)

predictions = model.predict(data_set)
predictions
# for i in range(18,predictions[0].size):
#     print(i)

#calculate accuracy
# print(y_test)
# score = accuracy_score(my_test,predictions)
# print(score)

[[0, 18, 32, 5], [0, 19, 32, 5], [0, 20, 32, 5], [0, 21, 32, 5], [0, 22, 32, 5], [0, 23, 32, 5], [0, 24, 32, 5], [0, 25, 32, 5], [0, 26, 32, 5], [0, 27, 32, 5], [0, 28, 32, 5], [0, 29, 32, 5], [0, 30, 32, 5], [0, 31, 32, 5], [0, 32, 32, 5], [0, 33, 32, 5], [0, 34, 32, 5]]

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1], dtype=int64)

In [22]:
dating_set_new = pd.read_csv('Speed Dating Data.csv',usecols = ['gender','age_o','dec_o','age'])
dating_set_new = dating_set_new.dropna()
dating_set_new.drop_duplicates(inplace=True)
df = dating_set_new[(dating_set_new.gender == 0) & (dating_set_new.age == 26) & (dating_set_new.dec_o == 0)]
df.drop_duplicates(inplace=True)
df

C:\Users\shubhampc\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

      gender  age_o  dec_o   age
80         0   27.0      0  26.0
89         0   24.0      0  26.0
91         0   22.0      0  26.0
95         0   25.0      0  26.0
96         0   30.0      0  26.0
323        0   23.0      0  26.0
324        0   21.0      0  26.0
325        0   28.0      0  26.0
446        0   26.0      0  26.0
1065       0   29.0      0  26.0
1070       0   32.0      0  26.0
1863       0   37.0      0  26.0
2824       0   42.0      0  26.0
3470       0   33.0      0  26.0
3650       0   34.0      0  26.0
5881       0   31.0      0  26.0
7098       0   20.0      0  26.0